### ISSUE TITLE
Yarn workspaces suggestion

### ISSUE THREAD

**Issue by Paulooze** [FRINXio/frinx-frontend#1]
I have a suggestion regarding a folder structure for yarn workspaces. I think that all projects should live in one directory like this:
```json
// package.json
"workspaces": [
    "packages/*"
]
```
The folder structure should then look like this:
- package.json
- packages
  - frinx-dashboard
    - src
    - package.json
    - .eslintrc.js
  - frinx-workflow-ui
    - src
    - package.json
    - .eslintrc.js

Here are (large) repositories that are using it like this: https://github.com/babel/babel, https://github.com/apollographql/apollo-tooling, https://github.com/facebook/react

**Comment by hotlib** [comment]
looks good, will adapt
